### ISSUE TITLE
sqlite3 over better-sqlite3

### ISSUE THREAD

**Issue by gespaltenlodert** [mateusabelli/refine-sqlite#8]
Hello Mateus.

I think it's great that there is finally a way to connect refine and sqlite. Thank you very much for that. But i´ve got a question.
Why have you choosen sqlite3 instead of better-sqlite3?

What was your motivation for this?

Thx a lot
Thomas

**Comment by mateusabelli** [comment]
Hello @gespaltenlodert thank you for your kind words!

I chose sqlite3 because it was the very first popular library that I found while planning the development of this project. I didn't even considered the fact that it was node-only and went on with the development.

Lately I've been working on the browser support with sql.js but it wasn't showing satisfactory results, so I'm considering making this data provider node-only and work to improve it.

With that said, better-sqlite3 seems to be an awesome suggestion, thank you Thomas!
Please let me know if you have any questions, I'll be available.
